spin_manifest_version = "1"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""
name = "spin-langchain-js"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-langchain-js"
source = "dist/spin-langchain-js.wasm"
exclude_files = ["**/node_modules"]
ai_models = ["llama2-chat", "codellama-instruct", "all-minikm-16-v2"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
